# Generated by Django 3.2 on 2022-09-19 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0005_auto_20220913_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reason', models.CharField(choices=[('wrong_item', 'Wrong Item'), ('damaged_item', 'Damaged Item'), ('item_not_received', 'Item Not Received')], max_length=20)),
                ('return_request_date', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.CharField(blank=True, max_length=200)),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.order')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Returns',
            },
        ),
    ]
