# Generated by Django 3.2 on 2022-09-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_alter_returns_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
